### ISSUE TITLE
Service kann manchmal keine Verbindung aufbauen

### ISSUE THREAD

**Issue by jwalteri** [ob-vss-ws19/blatt-4-petya#1]
Sehr geehrter Herr Braun,
ich habe folgendes Problem:
Ich versuche den MovieService mit meinem client.go zu testen. Dabei wird ein Movie erstellt und direkt darauf per GetMovie geholt.
Der MovieService und der Client starten erfolgreich. 
Das Problem: In vielen Fällen kann anscheinend der Client keine Verbindung zum MovieService herstellen. Meistens passiert das beim Aufruf von GetMovie. Ich erhalte folgende Fehlermeldung: {"id":"go.micro.client","code":408,"detail":"call timeout: context deadline exceeded","status":"Request Timeout"}
Entweder alles funktioniert perfekt, oder es kommt diese Fehlermeldung.
Es geht um den Branch Develop mit dem aktuellsten Commit.
Wissen Sie an was das liegen könnte?

Mein Vorgehen:
- main.go vom MovieService starten in einer Console
- in goland meinen client.go starten
Ergebnis:
Bei Erfolg: 
               - Service-Console gibt Log-Nachrichten aus
               - Client ruft erfolgreich GetMovie auf
Bei Misserfolg:
               - Service-Console gibt KEINE Log-Nachrichten aus
               - Client gibt oben genannte Fehlermeldung aus

Vielen Dank und beste Grüße

**Comment by obcode** [comment]
Das ist ein Timeout. Der kann natürlich jederzeit passieren, je nachdem was Ihre CPU sonst so zu tun hat.

Sie haben als Context meistens `context.TODO()`. Sie können in dem Context auch einen größeren Timeout setzen. 

```.go
const timeout = 10 * time.Second
ctx, cancel := context.WithTimeout(context.Background(), timeout)
defer cancel()

res, err := movieService.CreateMovie(ctx, &MovieService.CreateMovieMessage{
	Title: name,
})
```
